# Generated by Django 6.0.4 on 2026-04-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='glass_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='method',
            field=models.TextField(blank=True),
        ),
    ]
