# Generated by Django 6.0.4 on 2026-07-31 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='history',
        ),
    ]
