# Generated by Django 6.0.4 on 2026-04-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_cocktail_description_cocktail_glass_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
