# Generated by Django 6.0.4 on 2026-07-31 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_remove_cocktail_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cocktail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_obj', to='cocktails.cocktail'),
        ),
    ]
