# Generated by Django 6.0.4 on 2026-08-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_remove_cocktail_recipe_alter_recipe_cocktail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
