# Generated by Django 6.0.4 on 2026-04-22 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_alter_cocktail_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='glass_type',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='method',
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktails.history'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='recipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktails.recipe'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='cocktails.ingredient'),
        ),
    ]
