# Generated by Django 6.0.4 on 2026-07-24 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_alter_ingredient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='history',
        ),
        migrations.AddField(
            model_name='history',
            name='cocktail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cocktails.cocktail'),
        ),
    ]
