# Generated by Django 6.0.4 on 2026-08-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_thread_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
