# Generated by Django 5.1.3 on 2026-07-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0006_alter_cocktail_id_alter_history_id_and_more"),
        ("cocktails", "0006_remove_cocktail_history_history_cocktail"),
    ]

    operations = []
